### ISSUE TITLE
Change django settings to use HAB data

### ISSUE THREAD

**Issue by afzalhmd14** [krishraghuram/mess#13]
Change django database settings to use HAB data

**Comment by krishraghuram** [comment]
I am not sure, but I think what you mean is : 
Check out ways in which HAB data can be imported and exported from django admin. 

**About the data**

If you check out [rating/models.py](https://github.com/krishraghuram/mess/blob/master/rating/models.py), you will find that the Profile model contains the fields, 

- user
- rfid
- rollno
- name
- resident_hostel
- subscribed_hostel

The user field is just a foreign key with a django user object. It is used by django internally, and can be ignored, for most purposes. 
The rfid and rollno, are set the first time the user shows the card to system. Further, they cannot be modified in the admin interface. 
The name, resident_hostel and subscribed_hostel are the details that HAB has to provide. Thus, HAB will provide a datatbase of rollno, name, resident_hostel and subscribed_hostel. We will use the rollno to match the data, and insert the other three details. 

**How to get the data from CSV / EXCEL to django**
- Simple mysql replication will not work very well, since we will have to deal with the internal schema of django models. 
- The next option is to write a python script to do this. This will work fine, but we can do better.
- There are several django apps for exporting and importing data to the django admin. For example, 
* [Django Import Export](https://github.com/django-import-export/django-import-export)
* A small [tutorial](https://simpleisbetterthancomplex.com/packages/2016/08/11/django-import-export.html) on django import export.
- Using such a method, we make the "importing of data" loosely coupled to the "project" itself. Thus, changes to the project database schema, will not require changes in the way data is imported. 

Side Note : Django Import Export is also a good solution for #15. As they say, two birds in one stone.
